key: '=username'
elements:
    username:
        type: 'string'
    email:
        type: 'email'
    groups:
        type: 'checkbox'
    password:
        type: 'password'
    displayName:
        type: 'string'
    accessCode:
        type: 'hash'
    calCatetoryPermission:
        type: 'string'
    accessCodeEnabled:
        name: accessCodeEnabled
        type: toggle
    accessCodeValidUntil:
        name: accessCodeValidUntil
        type: datetime
    emaillist:
        name: emaillist
        type: string
    inactive:
        type: 'toggle'
