# Reservation:

lzy-reservation-info:
    de: ''
    _:  ''

reservation-count:
  de: 'Anzahl'
  _:  'Number'

lzy-timestamp:
  de: 'Eingang'
  _:  'Received'

'First Name':
  de: 'Vorname'
  _:  'First Name:'

'Last Name':
  de: 'Nachname:'
  _:  'Last Name:'

'E-Mail':
  de: 'E-Mail:'
  _:  'E-Mail:'

'lzy-reservation-count-label':
  de: 'Anzahl:'
  _:  'Count:'

'lzy-reservation-submit':
  de: 'Jetzt reservieren'
  _:  'Submit reservation'

'lzy-reservation-cancel':
  de: 'Abbrechen'
  _:  'Cancel'

lzy-reservation-aborted:
  de: |
    <p>Anmeldung abgebrochen.</p>
    <p><a href="./">Weiter...</a></p>
  _:  ':'

lzy-confirmation-response-subject:
  de: 'Reservationsbestätigung'
  _:  'Reservation confirmed'

lzy-reservation-full:
  de: '<p>Die Veranstaltung ist leider bereits ausgebucht.</p>'
  _:  '<p>Sorry, this event is already booked out.</p>'


lzy-reservation-timed-out:
  de: 'Die Zeit ist abgelaufen, bitte laden Sie die Seite erneut.'
  _:  'Time for making a reservation has expired. Please reload the page.'

lzy-reload:
  de: 'Neu laden'
  _:  'Reload'

lzy-confirmation-response-message:
  de: |
    Guten Tag {{ first_name-value }} {{ last_name-value }}

    Besten Dank, wir haben Ihre Reservation empfangen.
    Anzahl Plätze: {{ reservation-count-value }}

    Beste Grüsse

  _:  |
    Hello {{ first_name-value }} {{ last_name-value }}

    Thank you very much. We received your reservation.
    Number of seats: {{ reservation-count-value }}

    Regards

lzy-reservation-deadline-exceeded:
  de: 'Die Anmeldefrist ist am $date abgelaufen.'
  _:  'Registration deadline exeeded on $date.'

__END__
'':
  de: ':'
  _:  ':'

'':
  de: ':'
  _:  ':'

