# Reservation:

lzy-reservation-info:
    de: ''
    _:  ''

reservation-count:
  de: 'Anzahl'
  _:  'Number'

lzy-timestamp:
  de: 'Eingang'
  _:  'Received'

'First Name':
  de: 'Vorname'
  _:  'First Name:'

'Last Name':
  de: 'Nachname:'
  _:  'Last Name:'

'E-Mail':
  de: 'E-Mail:'
  _:  'E-Mail:'

'lzy-reservation-count-label':
  de: 'Anzahl:'
  _:  'Count:'

'lzy-reservation-submit':
  de: 'Jetzt reservieren'
  _:  'Submit reservation'

'lzy-reservation-cancel':
  de: 'Abbrechen'
  _:  'Cancel'

lzy-reservation-aborted:
  de: |
    <p>Anmeldung abgebrochen.</p>
    <p><a href="./">Weiter...</a></p>
  _:  ':'

lzy-confirmation-response-subject:
  de: 'Reservationsbestätigung'
  _:  'Reservation confirmed'

lzy-reservation-full:
  de: '<p>Die Veranstaltung ist ausgebucht.</p>'
  _:  '<p>Sorry, this event is fully booked.</p>'

lzy-reservation-full-error:
  de: '<p>Die Reservation konnte nicht ausgeführt werden, alle Plätze sind bereits ausgebucht.</p>'
  _:  "<p>Couldn't fullfill reservation, all we are fully booked.</p>"

lzy-registration-more-than:
  de: 'mehr als $moreThanThreshold'
  _:  'more than $moreThanThreshold'


lzy-reservation-timed-out:
  de: 'Die Zeit ist abgelaufen, bitte laden Sie die Seite erneut.'
  _:  'Time for making a reservation has expired. Please reload the page.'

lzy-reload:
  de: 'Neu laden'
  _:  'Reload'

lzy-confirmation-response-message:
  de: |
    Guten Tag {{ first_name-value }} {{ last_name-value }}

    Besten Dank, wir haben Ihre Reservation empfangen.
    Anzahl Plätze: {{ reservation-count-value }}

    Beste Grüsse

  _:  |
    Hello {{ first_name-value }} {{ last_name-value }}

    Thank you very much. We received your reservation.
    Number of seats: {{ reservation-count-value }}

    Regards

lzy-reservation-deadline-passed:
  de: 'Die Anmeldefrist ist abgelaufen.'
  _:  'Reservation deadline has passed.'

lzy-reservation-email-sent:
  de: '<p>Sie erhalten in Kürze eine Bestätigung per E-Mail.</p>'
  _:  '<p>You will receive a confirmation by e-mail shortly.</p>'

lzy-reservation-email-info:
  de: 'Wenn Sie Ihre E-Mail Adresse hier eingeben, erhalten Sie eine Bestästigung per E-Mail.'
  _:  'If you fill in your e-mail address, we will send you confirmation message.'


__END__
'':
  de: ':'
  _:  ':'

'':
  de: ':'
  _:  ':'

