

lzy-cal-event:
    de: Ereignis
    _: Event

lzy-cal-location:
    de: Ort
    _: Location

lzy-cal-date:
    de: 'Datum:'
    _: 'Date:'
lzy-cal-start-date-label:
    de: 'Datum:'
    _: 'Date:'
lzy-cal-end-date-label:
    de: 'Datum:'
    _: 'Date:'

lzy-cal-start-time-label:
    de: Zeit
    _: Time
lzy-cal-end-time-label:
    de: Zeit
    _: Time
lzy-cal-time:
    de: Zeit
    _: Time

lzy-cal-comment:
    de: Notiz
    _: Comment

lzy-cal-comment-placeholder:
    de: Notiz
    _: Comment

lzy-cal-delete-entry:
    de: Eintrag löschen
    _: Delete entry

lzy-cal-delete-entry-now:
    de: Löschen
    _:  Delete

lzy-cal-modif-entry:
    de: Eintrag ändern
    _: Modify Event

lzy-cal-new-entry:
    de: Neuer Eintrag
    _: New Event

lzy-cal-event-placeholder:
    de: Titel
    _:  title

lzy-cal-location-placeholder:
    de: Ort
    _:  Location

lzy-cal-legend-from:
    de: Von
    _:  From

lzy-cal-legend-till:
    de: Bis
    _:  Till

lzy-cal-category-all:
    de: ''
    _:  ''

lzy-cal-category-label:
    de: Kategorie
    _:  Category

lzy-cal-event-title:
    de: Bezeichnung
    _:  Event name

lzy-cal-allday-event:
    de: Ganztägig
    _:  Allday

# labels:
lzy-cal-label-prev:
    _:  '〈 '
lzy-cal-label-next:
    _:  ' 〉'
lzy-cal-label-prev-year:
    _:  '《'
lzy-cal-label-next-year:
    _:  '》'
lzy-cal-label-year:
    de: 'Jahr'
    _:  'Year'
lzy-cal-label-month:
    de: 'Monat'
    _:  'Month'
lzy-cal-label-week:
    de: 'Woche'
    _:  'Week'
lzy-cal-label-day:
    de: 'Tag'
    _:  'Day'
lzy-cal-label-today:
    de: 'Heute'
    _:  'Today'
lzy-cal-label-list:
    de: 'Listenansicht'
    _:  'List view'

lzy-cal-label-week-nr:
    de: 'KW'
    _:  'W'
lzy-cal-label-allday:
    de: 'Ganztag'
    _:  'all day'
lzy-cal-label-more-link:
    de: 'mehr'
    _:  'more'
lzy-cal-label-empty-list:
    de: 'leer'
    _:  'empty'
